source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails',                    '~> 5.1.4'
gem 'sqlite3'
gem 'puma',                     '~> 3.10'
gem 'bcrypt',                   '~> 3.1'
gem 'active_model_serializers'
gem 'tzinfo-data'

group :development, :test do
  gem 'byebug',                 platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'awesome_print'
  gem 'awesome_rails_console'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
end

group :development do
  gem 'listen',                 '~> 3.1'
  gem 'spring'
  gem 'spring-watcher-listen',  '~> 2.0'
end

group :test do
  gem 'shoulda-matchers'
  gem 'rspec-its'
  gem 'rspec-activemodel-mocks'
  gem 'shoulda-callback-matchers'
end
