# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9808822f812a26aaabc4dea6b034b694cf578adb949a4d690374de619f285431f2eb23ce0f3cb7f89a730c36fc3717667a759e7a169fdc9c26ae0427355e5389

test:
  secret_key_base: 313cf5595b06b5c331c1e24eaa384df136b230deb729a20468f30b88beb47351ae7f9e11d1b8e75f6ef5128f0d8a5dfa0b491076dc4db8324342680f2c05fde8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
